### ISSUE TITLE
Request for sharing Matlab code to generate ultrasound data using k-Wave simulation

### ISSUE THREAD

**Issue by Bilybill** [rehmanali1994/DixInversion4MedicalUltrasound#1]
I am currently working on a project that involves using k-Wave simulations to generate ultrasound data. I came across your GitHub repository and noticed that you have included simulated generated data but not the specific Matlab code for generating ultrasound data using k-Wave simulations.

I would be extremely grateful if you could kindly share the Matlab code that you used to generate the ultrasound data with k-Wave. Having access to this code would be extremely helpful for my project and allow me to better understand the process involved in generating ultrasound data with k-Wave simulations.

**Comment by rehmanali1994** [comment]
I unfortunately no longer have the exact k-Wave codes I used to make these simulations. Going forward, I will try to include the k-Wave codes that I used to generate the data. For now, I can recommend that you look at the following repository from a colleague of mine: https://github.com/thorstone25/qups

This QUPS package shows how to use k-Wave for generating pulse-echo ultrasound data (among many other very helpful things), and a lot of it is based on the same approach I used to generate my data. However, I think thorstone25 did a much better job than me when it came to streamlining the code and making it efficient. I would look to his code. He is a much better programmer than I am. Whereas I usually make code that only serves a teaching purpose, thorstone25 often makes codes that follow rigorous software engineering principles. As a result his code often scales well. He's actively looking to improve his QUPS library, so I'm sure he would appreciate any feedback on it.
